# Generated by Django 4.0.4 on 2022-05-04 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='answer',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='categroy',
            field=models.CharField(choices=[('AO', 'Account'), ('NR', 'Normal'), ('EC', 'Etc')], default='NR', max_length=2, verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='휴대폰번호'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(verbose_name='답변')),
                ('inpuiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.inquiry')),
            ],
        ),
    ]
